services:
  mysql:
    image: mysql:8.0
    container_name: user-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: mygorm
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    container_name: user-redis
    ports:
      - "6379:6379"

  app:
    build: .
    container_name: user-app
    ports:
      - "9090:9090"
    environment:
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mysql
      REDIS_ADDR: redis:6379
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
